stages:
  load_data:
    cmd: python src/stage_01_load_save.py
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - data/cat
      - data/dog